Update transformations.py
* argument direction no longer takes str, but int or bool (or, most correctly, globals ASCENDING and DESCENDING)
* function next() is deprecated

passing str for direction was giving error 
```
/usr/local/lib/python3.10/dist-packages/music21/scale/intervalNetwork.py in getNext(self, nodeStart, direction)
   1141                                      'postEdge', postEdge])
   1142             # return None
-> 1143             raise IntervalNetworkException('could not find any edges')
   1144 
   1145         # if we have multiple edges, we may need to select based on weight

IntervalNetworkException: could not find any edges
```

see https://web.mit.edu/music21/doc/moduleReference/moduleScale.html#music21.scale.ConcreteScale.nextPitch